export { getPosts } from './posts/getPosts'
export { getPostDetail } from './posts/getPostDetail'
export { getRecentPosts } from './posts/getRecentPosts'
export { getSimilarPosts } from './posts/getSimilarPosts'
export { getCategories } from './getCategories'
export { getCategoryPosts } from './getCategoryPosts'
export { submitComment } from './submitComment'
export { postSearch } from './postSearch'
